[package]
name = "scord"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
csv = "1.3"
rfd = "0.15"
anyhow = "1.0"
dirs = "5.0"
